Fix dependencies (#23)
* Revert "Dependencies: remove kotlin-compiler (#22)"

This reverts commit acddf3fc37b1c658040d95e834a44aa1c0edd44f.

* Fix dependencies

Revert acddf3fc37b1c658040d95e834a44aa1c0edd44f to fix 'org.jetbrains.kotlin.idea.KotlinFileType cannot be cast to org.jetbrains.kotlin.com.intellij.openapi.fileTypes.LanguageFileType' error. That error happens when using kotlin-compiler and kotlin-compiler-embeddable at the same time. However, if kotlin-compiler is removed, running Ank raises java.lang.NoClassDefFoundError: com/sun/jna/Native. This change recovers the use of kotlin-compiler and adds runtime dependencies from build.gradle instead of code.